import ctypes
import json
import os
from pathlib import Path
import shutil
import subprocess
from types import SimpleNamespace
import uuid

import pytest

from data_search import cli, config, user_folders
from data_search.engine import Engine


def test_windows_uses_redirected_known_folder_and_frees_result(monkeypatch, tmp_path):
    redirected = tmp_path / 'OneDrive' / '文档'
    redirected.mkdir(parents=True)
    value = ctypes.create_unicode_buffer(str(redirected))
    freed = []

    def known_folder(folder_id, flags, token, result):
        assert ctypes.string_at(folder_id, 16) == uuid.UUID('FDD39AD0-238F-46AF-ADB4-6C85480369C7').bytes_le
        assert flags == 0 and token is None
        result._obj.value = ctypes.addressof(value)
        return 0

    def free(pointer):
        freed.append(pointer.value)

    monkeypatch.setattr(user_folders.ctypes, 'windll', SimpleNamespace(
        shell32=SimpleNamespace(SHGetKnownFolderPath=known_folder),
        ole32=SimpleNamespace(CoTaskMemFree=free)), raising=False)
    monkeypatch.setattr(user_folders, 'sys', SimpleNamespace(platform='win32'))
    assert user_folders.documents_roots() == [str(redirected)]
    assert freed == [ctypes.addressof(value)]


@pytest.mark.parametrize('target', ['missing', 'home', 'root', 'failure'])
def test_windows_missing_or_broad_documents_never_falls_back(monkeypatch, tmp_path, target):
    monkeypatch.setattr(user_folders, 'sys', SimpleNamespace(platform='win32'))
    home = tmp_path / 'user'
    (home / 'Documents').mkdir(parents=True)
    monkeypatch.setattr(Path, 'home', lambda: home)

    def resolve_folder():
        if target == 'failure':
            raise OSError('Known folder lookup failed')
        return {'missing': str(home / 'gone'), 'home': str(home), 'root': home.anchor}[target]

    monkeypatch.setattr(user_folders, '_windows_documents', resolve_folder)
    assert user_folders.documents_roots() == []


@pytest.fixture
def linux_home(monkeypatch, tmp_path):
    home = tmp_path / 'user'
    home.mkdir()
    monkeypatch.setattr(Path, 'home', lambda: home)
    monkeypatch.setattr(user_folders, 'sys', SimpleNamespace(platform='linux'))
    monkeypatch.setenv('XDG_CONFIG_HOME', str(home / 'settings'))
    (home / 'settings').mkdir()
    return home


@pytest.mark.parametrize('absolute', [False, True])
def test_linux_xdg_documents_localized_path(linux_home, absolute):
    documents = linux_home / '资料 空间'
    documents.mkdir()
    selected = documents.as_posix() if absolute else '$HOME/资料 空间'
    (linux_home / 'settings' / 'user-dirs.dirs').write_text(
        f'# generated by xdg-user-dirs\nXDG_DOCUMENTS_DIR="{selected}"\n', encoding='utf-8')
    assert user_folders.documents_roots() == [str(documents)]


@pytest.mark.parametrize('selected', ['$HOME', '$HOME/gone', 'relative', '$(touch dangerous)', '$OTHER/docs', ''])
def test_linux_disabled_missing_or_invalid_xdg_never_uses_home_or_fallback(linux_home, selected):
    (linux_home / 'Documents').mkdir()
    (linux_home / 'settings' / 'user-dirs.dirs').write_text(f'XDG_DOCUMENTS_DIR="{selected}"\n', encoding='utf-8')
    assert user_folders.documents_roots() == []


def test_linux_conventional_documents_only_when_available(linux_home):
    assert user_folders.documents_roots() == []
    documents = linux_home / 'Documents'
    documents.mkdir()
    assert user_folders.documents_roots() == [str(documents)]


def test_init_missing_documents_requires_selection_and_machine_is_explicit(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(config, 'documents_roots', lambda: [])
    path = tmp_path / 'config.json'
    args = ['init', '--config', str(path), '--data-dir', str(tmp_path / 'index')]
    assert cli.main(args) == 1
    failure = json.loads(capsys.readouterr().out)
    assert failure['ok'] is False and '--root' in failure['error']['message']
    assert not path.exists()
    assert cli.main([*args, '--whole-machine']) == 0
    loaded = config.load_config(path)
    assert loaded['scope'] == 'machine' and loaded['roots'] == []


def test_init_explicit_directories_bypasses_documents_lookup(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(config, 'documents_roots', lambda: pytest.fail('explicit scope must not resolve Documents'))
    root = tmp_path / 'chosen'
    root.mkdir()
    path = tmp_path / 'config.json'
    assert cli.main(['init', '--config', str(path), '--data-dir', str(tmp_path / 'data'), '--root', str(root)]) == 0
    assert json.loads(capsys.readouterr().out)['roots'] == [str(root)]
    with pytest.raises(SystemExit):
        cli._parser().parse_args(['init', '--data-dir', str(tmp_path), '--root', str(root), '--whole-machine'])


@pytest.mark.parametrize('scope,roots', [('machine', []), ('directories', []), ('directories', ['chosen'])])
def test_saved_scope_does_not_use_new_defaults(tmp_path, monkeypatch, scope, roots):
    monkeypatch.setattr(config, 'documents_roots', lambda: pytest.fail('saved scope must not resolve Documents'))
    original = config.defaults(str(tmp_path / 'index'), [str(tmp_path / p) for p in roots])
    original['scope'] = scope
    path = tmp_path / 'config.json'
    config.atomic_json(path, original)
    loaded = config.load_config(path)
    assert (loaded['scope'], loaded['roots']) == (scope, original['roots'])


def test_default_scan_only_discovers_documents(tmp_path, monkeypatch):
    documents, unrelated = tmp_path / 'Documents', tmp_path / 'unrelated'
    documents.mkdir()
    unrelated.mkdir()
    (documents / 'inside.txt').write_text('inside')
    (unrelated / 'outside.txt').write_text('outside')
    monkeypatch.setattr(config, 'documents_roots', lambda: [str(documents)])
    monkeypatch.setattr('data_search.scope.discover_volumes', lambda: pytest.fail('default must not discover machine disks'))
    current = config.defaults(str(tmp_path / 'index'))
    current['semantic']['enabled'] = False
    current['indexing'].update(content_scope='none', semantic_scope='none')
    current['resource'].update(min_available_mb=0, min_free_disk_mb=0)
    engine = Engine(current)
    try:
        engine.scan_once()
        assert [row['path'] for row in engine.store.rows('SELECT path FROM documents')] == [str(documents / 'inside.txt')]
    finally:
        engine.close()


@pytest.mark.skipif(os.name != 'nt', reason='Windows installer parameter forwarding')
@pytest.mark.parametrize('mode', ['documents', 'machine', 'selected'])
def test_dsh_install_wrapper_passes_scope_without_selecting_machine_by_default(tmp_path, mode):
    release = tmp_path / 'release'
    (release / 'scripts').mkdir(parents=True)
    # Execute the real DSH wrapper against a capturing installer, without
    # modifying an installation or starting a daemon.
    (release / 'scripts' / 'install.ps1').write_text('''param(
    [string]$InstallDir, [string]$DataDir, [string[]]$Root, [string[]]$Exclude,
    [string]$Preset, [switch]$SkipModel, [switch]$NoAutostart, [switch]$WholeMachine
)
$result = @{roots=@($Root); wholeMachine=[bool]$WholeMachine}
[IO.File]::WriteAllText($DataDir, ($result | ConvertTo-Json -Compress))
''', encoding='utf-8')
    output = tmp_path / 'captured.json'
    roots = [str(tmp_path / "selected ' directory")] if mode == 'selected' else []
    request = tmp_path / 'request.json'
    request.write_text(json.dumps({'releaseDir': str(release), 'installDir': str(tmp_path / 'app'),
        'dataDir': str(output), 'roots': roots, 'wholeMachine': mode == 'machine', 'excludePaths': [],
        'preset': 'balanced', 'skipModel': True, 'noAutostart': True, 'modelDir': ''}), encoding='utf-8')
    wrapper = Path(__file__).resolve().parents[1] / 'plugins/deepseek-harness/install-wrapper.ps1'
    shell = shutil.which('powershell.exe') or shutil.which('pwsh.exe')
    assert shell
    result = subprocess.run([shell, '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass',
        '-File', str(wrapper), '-RequestPath', str(request)], capture_output=True, text=True,
        encoding='utf-8', errors='replace', timeout=30, creationflags=subprocess.CREATE_NO_WINDOW)
    assert result.returncode == 0, (result.stdout, result.stderr)
    assert json.loads(output.read_text(encoding='utf-8')) == {'roots': roots, 'wholeMachine': mode == 'machine'}
